pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }

    environment {
        CI = 'true'
    }

    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }

        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }

        stage('Manual Approval') {
            steps {
                script {
                    def userInput = input(
                        id: 'Proceed1',
                        message: 'Lanjutkan ke tahap Deploy?',
                        ok: 'Proceed'
                    )
                }
            }
        }

        stage('Deploy') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                echo '[INFO] Aplikasi berjalan. Menunggu selama 1 menit sebelum kill...'
                sleep(time: 1, unit: 'MINUTES') // ⏱️ Delay otomatis 1 menit
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}

